# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('NAO_VAI', 'Não poderei ir')], default='PENDENTE', max_length=15)),
                ('acompanhantes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_resposta', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Meu Aniversário', max_length=100)),
                ('data_evento', models.DateTimeField()),
                ('local', models.TextField()),
                ('limite_confirmacao', models.DateField(help_text='Data máxima para confirmar presença')),
            ],
        ),
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link_referencia', models.URLField(blank=True, help_text='Link de exemplo em alguma loja', null=True)),
                ('esta_reservado', models.BooleanField(default=False)),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentes_escolhidos', to='RSVP.convidado')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
