# Generated by Django 6.0.3 on 2026-03-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidado',
            name='acompanhantes',
        ),
        migrations.RemoveField(
            model_name='convidado',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='convidado',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convidado',
            name='primeiro_nome',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convidado',
            name='restricoes_alimentares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convidado',
            name='ultimo_nome',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convidado',
            name='status',
            field=models.CharField(default='CONFIRMADO', max_length=15),
        ),
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('restricoes_alimentares', models.TextField(blank=True, null=True)),
                ('convidado_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='RSVP.convidado')),
            ],
        ),
    ]
