# Generated by Django 6.0.3 on 2026-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0002_remove_convidado_acompanhantes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presente',
            options={},
        ),
        migrations.RemoveField(
            model_name='presente',
            name='link_referencia',
        ),
        migrations.RemoveField(
            model_name='presente',
            name='reservado_por',
        ),
        migrations.AddField(
            model_name='presente',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='Link de uma imagem do presente', null=True),
        ),
        migrations.AddField(
            model_name='presente',
            name='link_compra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presente',
            name='reservado_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
