# Generated by Django 6.0.3 on 2026-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0003_alter_presente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhante',
            name='restricoes_alimentares',
        ),
        migrations.RemoveField(
            model_name='convidado',
            name='restricoes_alimentares',
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convidado',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
